### PR TITLE
Add integration for the Immersive Engineering external heater

### PR DESCRIPTION
**Pull request by H-QueerCoded**
Allows the external heater to heat ranges and kitchenware. Not possible with CraftTweaker alone because of the need for new IE HeatableAdapters.

Not a perfect implementation:
- ~~Particles and~~ GUI for Stove/Hearth not displaying properly because the client is reading the TileEntity as unfueled ~~for some reason~~
- Required some minor changes to TileEntityRange to make fuelTimer and cooking values accessible to adapter

### CODE REVIEW

**Comment by H-QueerCoded** [comment]
Switching the clientside isFueled calls to isHeated fixed the particle issue and partially fixes the gui. The fuelTime indicator is not working properly but the heat bar is. 
Definitely a client/server communication thing, I've played around a bit with trying to use markDirty to resolve it but haven't found a good solution.
image

**Comment by Foreck1** [comment]
Really thankful for any dedicated support like this. I will leave this open for a little while to give you time to look into it some more.
Since I only have the most basic perception of what code can do (I'm the artist/designer, IItemStack is the modder but it was a commission), the process for adding native custom support for other blocks should be simpler, right?
Although right now I add the compatibility using CrT methods, I would love to have native compat for Pyrotech, Campfire, and BetterWithMods; I don't want to abuse your goodwill, but if you helped me out with those, I would gladly add you to the team members on CF and MD (assuming you like the idea).

Tell me when you want me to merge this.

**Comment by H-QueerCoded** [comment]
Yeah, most stuff will be simpler than this. I'd be happy to help out a bit with mod compat! I saw your CrT methods for Pyrotech and I think it should actually be simpler to do it natively.

**Comment by Foreck1** [comment]
Sorry for the mess, I reverted the merge because the other pull requests were conflicting. I could revert the revert if it was okay after all.

**Comment by H-QueerCoded** [comment]
All good, I was able to resolve the conflicts easily, it was just because the branches had separate edits to the integration class and build file.

Since the GUI is still not 100% working how I'd like it to I'll just wait and create a new PR once it is finished

**Comment by Foreck1** [comment]
Would it be better if you created a big PR with all three changes and anything else you want, and I closed the current ones?

**Pull request merged**
